# Generated by Django 6.0.4 on 2026-04-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='parsed_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='jobs_job_salary__2892b4_idx'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
