# Generated by Django 6.0.4 on 2026-04-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_statushistory_alter_application_parsed_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.application'),
        ),
    ]
