# Generated by Django 5.2.5 on 2026-06-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_statushistory_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-applied_at'], name='jobs_applic_applied_286417_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='jobs_applic_status_f83260_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_applic_job_id_a25382_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', '-applied_at'], name='jobs_applic_candida_3896a7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'is_deleted'], name='jobs_job_is_acti_f830d8_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['-changed_at'], name='jobs_status_changed_643c03_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['application', '-changed_at'], name='jobs_status_applica_ace932_idx'),
        ),
    ]
