# Generated by Django 5.2.5 on 2026-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_statushistory_options_job_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-saved_at']},
        ),
    ]
