# Generated by Django 5.2.5 on 2026-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
