# Generated by Django 6.0.4 on 2026-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
